# Generated by Django 4.2.5 on 2023-09-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerGroupName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('birthday', models.CharField(max_length=10)),
                ('taxIdentity', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('debt', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productTypeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DamageItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('note', models.TextField(blank=True)),
                ('totalAmount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('customer_need_return', models.DecimalField(decimal_places=0, max_digits=8)),
                ('customer_returned', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=100)),
                ('order_receiver', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('customer_need_return', models.DecimalField(decimal_places=0, max_digits=8)),
                ('customer_returned', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=0, max_digits=8)),
                ('receiverName', models.CharField(max_length=100)),
                ('receivingAccount', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentTypeName', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productGroupName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('costOfSales', models.DecimalField(decimal_places=0, max_digits=8)),
                ('price', models.DecimalField(decimal_places=0, max_digits=8)),
                ('Location', models.CharField(max_length=100)),
                ('Product_Barcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('total_quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('total_product', models.DecimalField(decimal_places=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('need_return_supplier', models.DecimalField(decimal_places=0, max_digits=8)),
                ('returned_supplier', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('total_quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('total_product', models.DecimalField(decimal_places=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('need_return_supplier', models.DecimalField(decimal_places=0, max_digits=8)),
                ('returned_supplier', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('total_quantity', models.DecimalField(decimal_places=0, max_digits=8)),
                ('total_product', models.DecimalField(decimal_places=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('supplier_need_return', models.DecimalField(decimal_places=0, max_digits=8)),
                ('supplier_returned', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiptTypeName', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reciepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=0, max_digits=8)),
                ('payerName', models.CharField(max_length=100)),
                ('paymentAccount', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('total_after_discount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('fee_return', models.DecimalField(decimal_places=0, max_digits=8)),
                ('customer_need_return', models.DecimalField(decimal_places=0, max_digits=8)),
                ('customer_returned', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='StockTakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('finishedAt', models.DateTimeField(auto_now_add=True)),
                ('realAmount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('actualTotalValue', models.DecimalField(decimal_places=0, max_digits=12)),
                ('amountDifferences', models.DecimalField(decimal_places=0, max_digits=8)),
                ('increaseAmount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('increaseValue', models.DecimalField(decimal_places=0, max_digits=8)),
                ('decreaseAmount', models.DecimalField(decimal_places=0, max_digits=8)),
                ('decreaseValue', models.DecimalField(decimal_places=0, max_digits=8)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('businessCode', models.CharField(max_length=13)),
                ('debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalPurchase', models.DecimalField(decimal_places=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
