# Generated by Django 4.2.5 on 2023-09-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='damageitems',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoices',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='accounting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Sales_Form',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Sales_Link',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reciepts',
            name='accounting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='return',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
